services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mpdata:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  postgre:
    image: postgres:14-alpine
    container_name: database_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: salman
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: minkey
    volumes:
      - pgdata:/var/lib/postgresql/data
  postgretest:
    image: postgres:14-alpine
    container_name: database_postgres_test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: salman
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    volumes:
      - pgdatatest:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdatatest:
  mpdata:
